openapi: 3.0.4 # VSCode extension does not support 3.1
info:
  title: Leaderboard Apex Service API
  version: 0.0.1
  description: A simple API for storing and retrieving player scores.
paths:
  /:
    get:
      summary: Simple health check or root handler
      responses:
        "200":
          description: Successful response

  /api/scores:
    post:
      summary: Accepts player name and score; returns a generated ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlayerInputData"
      responses:
        "201":
          description: Score successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneratedIdData"
        "400":
          description: Bad Request (e.g. invalid body)
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string

  /api/scores/{player_id}:
    get:
      summary: Retrieves a player's info by ID
      parameters:
        - name: player_id
          in: path
          required: true
          description: The ID of the player entry
          schema:
            type: string
      responses:
        "200":
          description: All ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayerData"
        "400":
          description: Bad Request (e.g. malformed player id)
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: ID not found
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    PlayerInputData:
      type: object
      required:
        - player_name
        - player_score
      properties:
        player_name:
          type: string
        player_score:
          type: number
          format: double
    PlayerData:
      type: object
      required:
        - player_id
        - player_name
        - player_score
      properties:
        player_id:
          type: string
        player_name:
          type: string
        player_score:
          type: number
          format: double

    GeneratedIdData:
      type: object
      additionalProperties: false
      required:
        - player_id
      properties:
        player_id:
          type: string
          description: The generated unique ID for the score entry
