openapi: 3.0.4 # TODO: bug with VSCode extension not supporting  support 3.1
info:
  title: Leaderboard Apex Service API
  version: 0.0.1
  description: A simple API for storing and retrieving player scores.
paths:
  /:
    get:
      summary: Simple health check or root handler
      responses:
        "200":
          description: Successful response

  /api/v1/scores:
    post:
      summary: Accepts player name and score; returns a generated ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewPlayerRequest"
      responses:
        "201":
          description: Score successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneratedIdResponse"
        "400":
          description: Bad Request (e.g. invalid body)
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string

  /api/v1/scores/{player_id}:
    get:
      summary: Retrieves a player's info by ID
      parameters:
        - name: player_id
          in: path
          required: true
          description: The ID of the player entry
          schema:
            type: string
      responses:
        "200":
          description: All ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayerDataResponse"
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: ID not found
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string

  /api/v1/scores/{player_id}/increment:
    post:
      summary: Increments the score (supports negative values for decrementing)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IncrementScoreRequest"
      parameters:
        - name: player_id
          in: path
          required: true
          description: The ID of the player entry
          schema:
            type: string
      responses:
        "200":
          description: All ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IncrementScoreResponse"
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: ID not found
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    NewPlayerRequest:
      type: object
      additionalProperties: false
      required:
        - player_name
        - player_score
      properties:
        player_name:
          type: string
        player_score:
          type: number
          format: double

    IncrementScoreRequest:
      type: object
      additionalProperties: false
      required:
        - amount
      properties:
        amount:
          type: number
          format: double

    PlayerDataResponse:
      type: object
      additionalProperties: false
      required:
        - player_id
        - player_name
        - player_score
      properties:
        player_id:
          type: string
        player_name:
          type: string
        player_score:
          type: number
          format: double

    GeneratedIdResponse:
      type: object
      additionalProperties: false
      required:
        - player_id
      properties:
        player_id:
          type: string
          description: The generated unique ID for a player entry

    IncrementScoreResponse:
      type: object
      additionalProperties: false
      required:
        - score
      properties:
        score:
          type: number
          format: double
          description: Score after incrementing
